package ragamuffin.world;

/**
 * Types of landmarks in the British town.
 */
public enum LandmarkType {
    PARK,
    GREGGS,
    OFF_LICENCE,
    CHARITY_SHOP,
    JEWELLER,
    OFFICE_BUILDING,
    JOB_CENTRE,
    INDUSTRIAL_ESTATE,
    BOOKIES,
    TERRACED_HOUSE,
    KEBAB_SHOP,
    LAUNDERETTE,
    TESCO_EXPRESS,
    PUB,
    PAWN_SHOP,
    BUILDERS_MERCHANT,
    WAREHOUSE,
    CHIPPY,
    NEWSAGENT,
    GP_SURGERY,
    PRIMARY_SCHOOL,
    COMMUNITY_CENTRE,
    CHURCH,
    TAXI_RANK,
    CAR_WASH,
    COUNCIL_FLATS,
    PETROL_STATION,
    NANDOS,
    BARBER,
    NAIL_SALON,
    WETHERSPOONS,
    CORNER_SHOP,
    BETTING_SHOP,
    PHONE_REPAIR,
    CASH_CONVERTER,
    LIBRARY,
    FIRE_STATION
}
