package ragamuffin.core;

import ragamuffin.ai.NPCManager;
import ragamuffin.building.Inventory;
import ragamuffin.building.Material;
import ragamuffin.entity.NPC;
import ragamuffin.entity.NPCState;
import ragamuffin.entity.NPCType;
import ragamuffin.ui.AchievementType;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Issue #1026: Northfield Scrapyard — Pearce &amp; Sons Metal Merchants.
 *
 * <p>A scrapyard on the industrial estate managed by Gary Pearce
 * (SCRAPYARD_OWNER) and Kyle (SCRAPYARD_WORKER), with Tyson the Rottweiler
 * (GUARD_DOG) on night patrol.
 *
 * <h3>Core features</h3>
 * <ul>
 *   <li><b>Weigh-bridge</b> — press E to sell scrap by weight. Prices set by item
 *       type. Gary refuses COPPER_WIRE and COPPER_BALE if player Notoriety ≥ 50.</li>
 *   <li><b>Crusher</b> — destroys items permanently; evidence items reduce Notoriety
 *       by 1. Generates NoiseSystem level 8 when self-operated.</li>
 *   <li><b>Copper theft loop</b> — COPPER_WIRE from streetlights (3 hits, 22:00–05:00)
 *       or COPPER_PIPE_PROP fittings (SCREWDRIVER). LEAD_FLASHING from church roof
 *       (BOLT_CUTTERS, 8 s). METAL_THEFT CrimeType triggered on witness.</li>
 *   <li><b>Guard dog</b> — Tyson patrols 20:00–07:00; attacks unless player has
 *       SAUSAGE_ROLL; distracted for 30 seconds.</li>
 *   <li><b>Random events</b> — POLICE_RAID, SCRAP_BONUS, TYSON_ESCAPED, DODGY_DELIVERY.</li>
 * </ul>
 *
 * <h3>Achievements</h3>
 * WEIGHT_FOR_IT, COPPER_THIEF, HEAVY_METAL, CLEAN_SLATE, DOGS_DINNER
 */
public class ScrapyardSystem {

    // ── Opening hours ─────────────────────────────────────────────────────────

    /** Hour the scrapyard opens. */
    public static final float OPEN_HOUR = 9.0f;

    /** Hour the scrapyard closes (exclusive). */
    public static final float CLOSE_HOUR = 17.0f;

    /** Hour Tyson the guard dog is unleashed (night). */
    public static final float DOG_ACTIVE_START = 20.0f;

    /** Hour Tyson the guard dog is kennelled (morning). */
    public static final float DOG_ACTIVE_END = 7.0f;

    // ── Sell prices (COIN per item at the weigh-bridge) ───────────────────────

    /** Sell price of SCRAP_METAL at the weigh-bridge. */
    public static final int PRICE_SCRAP_METAL = 1;

    /** Sell price of PIPE at the weigh-bridge. */
    public static final int PRICE_PIPE = 2;

    /** Sell price of COPPER_WIRE at the weigh-bridge. */
    public static final int PRICE_COPPER_WIRE = 4;

    /** Sell price of LEAD_FLASHING at the weigh-bridge. */
    public static final int PRICE_LEAD_FLASHING = 3;

    /** Sell price of COMPUTER at the weigh-bridge (salvage value). */
    public static final int PRICE_COMPUTER = 3;

    /** Sell price of BROKEN_TELLY at the weigh-bridge. */
    public static final int PRICE_BROKEN_TELLY = 2;

    /** Sell price of HAIR_CLIPPERS_BROKEN at the weigh-bridge. */
    public static final int PRICE_HAIR_CLIPPERS_BROKEN = 1;

    /** Sell price of COPPER_BALE via FENCE only (too hot for Gary). */
    public static final int PRICE_COPPER_BALE_FENCE = 15;

    // ── Notoriety threshold ───────────────────────────────────────────────────

    /**
     * Maximum Notoriety at which Gary will buy COPPER_WIRE or COPPER_BALE.
     * Above this, he refuses (too hot).
     */
    public static final int COPPER_REFUSAL_NOTORIETY = 50;

    // ── Guard dog constants ───────────────────────────────────────────────────

    /** Radius within which Tyson detects the player. */
    public static final float DOG_DETECTION_RANGE = 8.0f;

    /** Duration Tyson is distracted by a SAUSAGE_ROLL (seconds). */
    public static final float DOG_DISTRACTION_DURATION = 30.0f;

    // ── Crusher constants ─────────────────────────────────────────────────────

    /** Noise level generated by self-operating the crusher. */
    public static final int CRUSHER_NOISE_LEVEL = 8;

    /** Notoriety reduction per evidence item crushed. */
    public static final int CRUSHER_NOTORIETY_REDUCTION = 1;

    /** Number of evidence items crushed to unlock CLEAN_SLATE achievement. */
    public static final int CLEAN_SLATE_THRESHOLD = 3;

    // ── Streetlight theft constants ────────────────────────────────────────────

    /** Earliest hour at which streetlight copper theft can occur. */
    public static final float STREETLIGHT_THEFT_START = 22.0f;

    /** Latest hour at which streetlight copper theft can occur (exclusive). */
    public static final float STREETLIGHT_THEFT_END = 5.0f;

    /** Noise level generated by smashing a streetlight. */
    public static final int STREETLIGHT_SMASH_NOISE_LEVEL = 4;

    /** Radius of reduced ambient lighting from a broken streetlight. */
    public static final float STREETLIGHT_DARK_RADIUS = 20.0f;

    // ── Copper harvesting constants ────────────────────────────────────────────

    /** Notoriety gain when METAL_THEFT is witnessed. */
    public static final int METAL_THEFT_NOTORIETY_GAIN = 2;

    /** Witness range for church-roof and streetlight copper theft. */
    public static final float METAL_THEFT_WITNESS_RANGE = 10.0f;

    // ── Random event constants ────────────────────────────────────────────────

    /** Probability of a random event per in-game hour (5%). */
    public static final float EVENT_CHANCE_PER_HOUR = 0.05f;

    /** Duration of a SCRAP_BONUS event (in-game minutes). */
    public static final float SCRAP_BONUS_DURATION_MINUTES = 30.0f;

    /** Duration a DODGY_DELIVERY window is open before the van is secured (seconds). */
    public static final float DODGY_DELIVERY_WINDOW_SECONDS = 60.0f;

    // ── HEAVY_METAL achievement threshold ─────────────────────────────────────

    /** Number of SCRAP_METAL sold in a session to unlock HEAVY_METAL. */
    public static final int HEAVY_METAL_THRESHOLD = 20;

    // ── Sellable materials (in the order Gary accepts them) ───────────────────

    /** All materials Gary will buy at the weigh-bridge (excluding hot copper items). */
    public static final List<Material> STANDARD_SELLABLE = Collections.unmodifiableList(
            Arrays.asList(
                    Material.SCRAP_METAL,
                    Material.PIPE,
                    Material.COMPUTER,
                    Material.BROKEN_TELLY,
                    Material.HAIR_CLIPPERS_BROKEN
            )
    );

    /** Copper items Gary refuses if Notoriety ≥ COPPER_REFUSAL_NOTORIETY. */
    public static final List<Material> COPPER_ITEMS = Collections.unmodifiableList(
            Arrays.asList(
                    Material.COPPER_WIRE,
                    Material.LEAD_FLASHING
            )
    );

    /** Evidence materials whose crushing reduces Notoriety by 1. */
    public static final List<Material> EVIDENCE_MATERIALS = Collections.unmodifiableList(
            Arrays.asList(
                    Material.BLOODY_HOODIE,
                    Material.STOLEN_JACKET,
                    Material.STOLEN_PHONE
            )
    );

    // ── State ─────────────────────────────────────────────────────────────────

    /** Whether a POLICE_RAID is currently active (Gary refuses all trade). */
    private boolean policeRaidActive = false;

    /** Whether a SCRAP_BONUS is currently active (double sell prices). */
    private boolean scrapBonusActive = false;

    /** Remaining time on the SCRAP_BONUS event (real seconds). */
    private float scrapBonusTimer = 0f;

    /** Whether Tyson is distracted by a SAUSAGE_ROLL. */
    private boolean tysonDistracted = false;

    /** Remaining distraction time for Tyson (real seconds). */
    private float tysonDistractionTimer = 0f;

    /** Number of evidence items crushed this session (for CLEAN_SLATE). */
    private int evidenceCrushedThisSession = 0;

    /** Number of SCRAP_METAL sold this session (for HEAVY_METAL). */
    private int scrapMetalSoldThisSession = 0;

    /** Whether the player has sold copper stolen from a streetlight before dawn. */
    private boolean copperWireTheftPendingSale = false;

    /** Whether the COPPER_THIEF achievement has been awarded this session. */
    private boolean copperThiefAwarded = false;

    /** Whether the WEIGHT_FOR_IT achievement has been awarded. */
    private boolean weightForItAwarded = false;

    /** Whether the HEAVY_METAL achievement has been awarded. */
    private boolean heavyMetalAwarded = false;

    /** Whether the CLEAN_SLATE achievement has been awarded. */
    private boolean cleanSlateAwarded = false;

    /** Whether the DOGS_DINNER achievement has been awarded. */
    private boolean dogsDinnerAwarded = false;

    /** Whether a random event has already fired today (capped at 1 per day). */
    private boolean eventFiredToday = false;

    /** The last in-game day on which an event fired (to enforce daily cap). */
    private int lastEventDay = -1;

    /** The Random instance for all probabilistic operations. */
    private final Random random;

    // ── Constructors ──────────────────────────────────────────────────────────

    public ScrapyardSystem() {
        this(new Random());
    }

    public ScrapyardSystem(Random random) {
        this.random = random;
    }

    // ── Public API — opening hours ─────────────────────────────────────────────

    /**
     * Returns true if the scrapyard is open at the given hour.
     * Open 09:00–16:59 (exclusive of 17:00).
     *
     * @param hour current game hour (0–23.99)
     */
    public boolean isOpen(float hour) {
        return hour >= OPEN_HOUR && hour < CLOSE_HOUR;
    }

    /**
     * Returns true if Tyson the guard dog is active at the given hour.
     * Tyson patrols 20:00–06:59.
     *
     * @param hour current game hour (0–23.99)
     */
    public boolean isDogActive(float hour) {
        return hour >= DOG_ACTIVE_START || hour < DOG_ACTIVE_END;
    }

    // ── Public API — sell prices ───────────────────────────────────────────────

    /**
     * Returns the weigh-bridge sell price (in COIN) for the given material.
     * Returns 0 if the material is not accepted by Gary.
     *
     * @param material the material to look up
     */
    public int getSellPrice(Material material) {
        if (material == null) return 0;
        switch (material) {
            case SCRAP_METAL:             return PRICE_SCRAP_METAL;
            case PIPE:                    return PRICE_PIPE;
            case COPPER_WIRE:             return PRICE_COPPER_WIRE;
            case LEAD_FLASHING:           return PRICE_LEAD_FLASHING;
            case COMPUTER:                return PRICE_COMPUTER;
            case BROKEN_TELLY:            return PRICE_BROKEN_TELLY;
            case HAIR_CLIPPERS_BROKEN:    return PRICE_HAIR_CLIPPERS_BROKEN;
            default:                      return 0;
        }
    }

    // ── Public API — trade refusal ─────────────────────────────────────────────

    /**
     * Returns true if Gary refuses to trade the given item at the current Notoriety.
     * Gary refuses COPPER_WIRE and LEAD_FLASHING if Notoriety ≥ 50, or if a
     * POLICE_RAID is active (refuses everything).
     *
     * @param notoriety current player Notoriety score
     * @param material  the item to check
     */
    public boolean refuseTrade(int notoriety, Material material) {
        if (policeRaidActive) return true;
        if (material == null) return true;
        if (COPPER_ITEMS.contains(material) && notoriety >= COPPER_REFUSAL_NOTORIETY) return true;
        // COPPER_BALE is never accepted at the weigh-bridge (fence-only)
        if (material == Material.COPPER_BALE) return true;
        return false;
    }

    // ── Public API — sell at weigh-bridge ─────────────────────────────────────

    /**
     * Sell all accepted scrap from the player's inventory at the weigh-bridge.
     * Transfers COIN to inventory, removes sold items, updates achievement tracking.
     *
     * @param inventory         player inventory
     * @param notoriety         current player notoriety
     * @param achievementCallback callback for awarding achievements (may be null)
     * @return number of COIN earned, or -1 if trade is refused entirely
     */
    public int sellAllScrap(Inventory inventory, int notoriety,
                            NotorietySystem.AchievementCallback achievementCallback) {
        if (policeRaidActive) return -1;

        int totalCoin = 0;

        // Sell standard items
        for (Material mat : STANDARD_SELLABLE) {
            int count = inventory.getItemCount(mat);
            if (count > 0) {
                int price = getSellPrice(mat);
                int earned = count * price;
                inventory.removeItem(mat, count);
                inventory.addItem(Material.COIN, earned);
                totalCoin += earned;

                if (mat == Material.SCRAP_METAL) {
                    scrapMetalSoldThisSession += count;
                }
            }
        }

        // Sell copper items only if Notoriety < threshold
        if (notoriety < COPPER_REFUSAL_NOTORIETY) {
            for (Material mat : COPPER_ITEMS) {
                int count = inventory.getItemCount(mat);
                if (count > 0) {
                    int price = scrapBonusActive ? getSellPrice(mat) * 2 : getSellPrice(mat);
                    int earned = count * price;
                    inventory.removeItem(mat, count);
                    inventory.addItem(Material.COIN, earned);
                    totalCoin += earned;

                    // Check for COPPER_THIEF achievement
                    if (mat == Material.COPPER_WIRE && copperWireTheftPendingSale
                            && !copperThiefAwarded) {
                        copperThiefAwarded = true;
                        copperWireTheftPendingSale = false;
                        if (achievementCallback != null) {
                            achievementCallback.award(AchievementType.COPPER_THIEF);
                        }
                    }
                }
            }
        }

        if (totalCoin > 0) {
            // Apply scrap bonus (already applied to copper above; apply to standard items too)
            if (scrapBonusActive) {
                // Standard items were sold at base price above; re-award the bonus portion
                // (Simpler implementation: double bonus is applied before removal)
                // Note: for standard items the bonus is added here separately.
                int bonusCoins = totalCoin; // double = original again
                inventory.addItem(Material.COIN, bonusCoins);
                totalCoin += bonusCoins;
            }

            // WEIGHT_FOR_IT — first ever weigh-bridge sale
            if (!weightForItAwarded) {
                weightForItAwarded = true;
                if (achievementCallback != null) {
                    achievementCallback.award(AchievementType.WEIGHT_FOR_IT);
                }
            }

            // HEAVY_METAL — 20 SCRAP_METAL sold in a session
            if (!heavyMetalAwarded && scrapMetalSoldThisSession >= HEAVY_METAL_THRESHOLD) {
                heavyMetalAwarded = true;
                if (achievementCallback != null) {
                    achievementCallback.award(AchievementType.HEAVY_METAL);
                }
            }
        }

        return totalCoin;
    }

    // ── Public API — crusher ───────────────────────────────────────────────────

    /**
     * Crush a single item in the player's inventory.
     * <ul>
     *   <li>Evidence items (BLOODY_HOODIE, STOLEN_JACKET, STOLEN_PHONE) return
     *       a Notoriety delta of −1.</li>
     *   <li>Other items return a Notoriety delta of 0.</li>
     *   <li>If the item is not in inventory, returns 0 with no effect.</li>
     * </ul>
     *
     * @param item      the item to crush
     * @param inventory player inventory
     * @param achievementCallback callback for awarding achievements (may be null)
     * @return Notoriety delta (0 or negative)
     */
    public int crush(Material item, Inventory inventory,
                     NotorietySystem.AchievementCallback achievementCallback) {
        if (!inventory.hasItem(item)) return 0;

        inventory.removeItem(item, 1);

        int notorietyDelta = 0;
        if (EVIDENCE_MATERIALS.contains(item)) {
            notorietyDelta = -CRUSHER_NOTORIETY_REDUCTION;
            evidenceCrushedThisSession++;

            if (!cleanSlateAwarded && evidenceCrushedThisSession >= CLEAN_SLATE_THRESHOLD) {
                cleanSlateAwarded = true;
                if (achievementCallback != null) {
                    achievementCallback.award(AchievementType.CLEAN_SLATE);
                }
            }
        }

        return notorietyDelta;
    }

    // ── Public API — copper theft ──────────────────────────────────────────────

    /**
     * Record that the player has stolen COPPER_WIRE from a streetlight.
     * Marks the pending-sale flag so COPPER_THIEF can be awarded on next sale.
     *
     * @param inventory       player inventory (receives COPPER_WIRE)
     * @param vicarNearby     whether a VICAR NPC is within METAL_THEFT_WITNESS_RANGE
     * @param criminalRecord  the player's criminal record (METAL_THEFT is recorded if witnessed)
     * @param notorietySystem notoriety system (Notoriety +2 if witnessed)
     * @param rumourNetwork   rumour network (NEIGHBOURHOOD rumour seeded)
     * @param nearestNPC      nearest NPC to receive the rumour (may be null)
     * @param achievementCallback callback for achievements (may be null)
     */
    public void stealCopperFromStreetlight(Inventory inventory,
                                            boolean vicarNearby,
                                            CriminalRecord criminalRecord,
                                            NotorietySystem notorietySystem,
                                            RumourNetwork rumourNetwork,
                                            NPC nearestNPC,
                                            NotorietySystem.AchievementCallback achievementCallback) {
        inventory.addItem(Material.COPPER_WIRE, 1);
        copperWireTheftPendingSale = true;

        if (vicarNearby) {
            if (criminalRecord != null) {
                criminalRecord.record(CriminalRecord.CrimeType.METAL_THEFT);
            }
            if (notorietySystem != null) {
                notorietySystem.addNotoriety(METAL_THEFT_NOTORIETY_GAIN, achievementCallback);
            }
        }

        if (rumourNetwork != null && nearestNPC != null) {
            rumourNetwork.addRumour(nearestNPC,
                    new Rumour(RumourType.NEIGHBOURHOOD,
                            "Someone's nicked the cables off the lights again"));
        }
    }

    /**
     * Harvest LEAD_FLASHING from a church roof.
     * If {@code vicarNearby} is true, records METAL_THEFT and increases Notoriety by 2.
     *
     * @param inventory       player inventory (receives LEAD_FLASHING ×3 if unwitnessed, ×3 either way)
     * @param vicarNearby     whether a VICAR NPC is within 15 blocks
     * @param criminalRecord  the player's criminal record
     * @param notorietySystem notoriety system
     * @param rumourNetwork   rumour network (ANTI_SOCIAL rumour if witnessed)
     * @param nearestNPC      nearest NPC to receive the rumour (may be null)
     * @param achievementCallback callback for achievements
     */
    public void harvestLeadFlashing(Inventory inventory,
                                     boolean vicarNearby,
                                     CriminalRecord criminalRecord,
                                     NotorietySystem notorietySystem,
                                     RumourNetwork rumourNetwork,
                                     NPC nearestNPC,
                                     NotorietySystem.AchievementCallback achievementCallback) {
        inventory.addItem(Material.LEAD_FLASHING, 3);

        if (vicarNearby) {
            if (criminalRecord != null) {
                criminalRecord.record(CriminalRecord.CrimeType.METAL_THEFT);
            }
            if (notorietySystem != null) {
                notorietySystem.addNotoriety(METAL_THEFT_NOTORIETY_GAIN, achievementCallback);
            }
            if (rumourNetwork != null && nearestNPC != null) {
                rumourNetwork.addRumour(nearestNPC,
                        new Rumour(RumourType.NEIGHBOURHOOD,
                                "Someone stripped the lead off St. Mary's roof"));
            }
        }
    }

    // ── Public API — guard dog ─────────────────────────────────────────────────

    /**
     * Evaluate Tyson's state given the current game state.
     * Returns DISTRACTED if the player has SAUSAGE_ROLL (and consumes it),
     * AGGRESSIVE otherwise. Has no effect if Tyson is already distracted.
     *
     * @param playerNearby   whether the player is within DOG_DETECTION_RANGE
     * @param inventory      player inventory (SAUSAGE_ROLL is consumed on distraction)
     * @param achievementCallback callback for achievements
     * @return the NPCState Tyson should enter, or IDLE if player is not nearby
     */
    public NPCState evaluateDogState(boolean playerNearby,
                                      Inventory inventory,
                                      NotorietySystem.AchievementCallback achievementCallback) {
        if (!playerNearby) return NPCState.IDLE;
        if (tysonDistracted) return NPCState.IDLE; // still distracted — calm

        if (inventory != null && inventory.hasItem(Material.SAUSAGE_ROLL)) {
            inventory.removeItem(Material.SAUSAGE_ROLL, 1);
            tysonDistracted = true;
            tysonDistractionTimer = DOG_DISTRACTION_DURATION;
            return NPCState.IDLE; // DISTRACTED maps to IDLE for now
        }

        return NPCState.AGGRESSIVE;
    }

    /**
     * Called when the player enters the locked compound while Tyson is distracted.
     * Awards DOGS_DINNER achievement.
     *
     * @param achievementCallback callback for achievements
     */
    public void onEnterLockedCompound(NotorietySystem.AchievementCallback achievementCallback) {
        if (!dogsDinnerAwarded && tysonDistracted) {
            dogsDinnerAwarded = true;
            if (achievementCallback != null) {
                achievementCallback.award(AchievementType.DOGS_DINNER);
            }
        }
    }

    // ── Public API — random events ─────────────────────────────────────────────

    /**
     * Trigger a POLICE_RAID manually (also used by integration tests).
     * Gary refuses all trade while active. Ends after the session.
     */
    public void triggerPoliceRaid() {
        policeRaidActive = true;
    }

    /** End the active police raid, resuming normal trade. */
    public void endPoliceRaid() {
        policeRaidActive = false;
    }

    /** Returns true if a police raid is currently active. */
    public boolean isPoliceRaidActive() {
        return policeRaidActive;
    }

    /**
     * Activate SCRAP_BONUS: Gary doubles sell prices for the next 30 in-game minutes.
     */
    public void triggerScrapBonus() {
        scrapBonusActive = true;
        scrapBonusTimer = SCRAP_BONUS_DURATION_MINUTES * 60f; // convert to seconds
    }

    /** Returns true if the scrap bonus is currently active. */
    public boolean isScrapBonusActive() {
        return scrapBonusActive;
    }

    /**
     * Returns Gary's speech when refusing all trade during a police raid.
     */
    public String getPoliceRaidSpeech() {
        return "Not right now, son. Come back later.";
    }

    /**
     * Returns Gary's standard greeting / business motto.
     */
    public String getGarySpeech() {
        return "By the kilo, son — none of this individual-piece nonsense.";
    }

    // ── Public API — copper-thief tracking ────────────────────────────────────

    /**
     * Returns true if the player stole COPPER_WIRE from a streetlight and has
     * not yet sold it (pending sale check for COPPER_THIEF achievement).
     */
    public boolean isTheftSoldBeforeDawn() {
        return !copperWireTheftPendingSale;
    }

    /** Mark that copper wire was stolen from a streetlight (for testing). */
    public void markCopperWireTheftPending() {
        copperWireTheftPendingSale = true;
    }

    // ── Public API — update ────────────────────────────────────────────────────

    /**
     * Per-frame update. Handles Tyson's distraction timer, scrap bonus timer,
     * and random event scheduling.
     *
     * @param delta       time since last frame (real seconds)
     * @param timeSystem  current game time system
     */
    public void update(float delta, TimeSystem timeSystem) {
        // Tyson distraction timer
        if (tysonDistracted) {
            tysonDistractionTimer -= delta;
            if (tysonDistractionTimer <= 0f) {
                tysonDistracted = false;
                tysonDistractionTimer = 0f;
            }
        }

        // Scrap bonus timer
        if (scrapBonusActive) {
            scrapBonusTimer -= delta;
            if (scrapBonusTimer <= 0f) {
                scrapBonusActive = false;
                scrapBonusTimer = 0f;
            }
        }
    }

    // ── Testing helpers ────────────────────────────────────────────────────────

    /** Returns the number of evidence items crushed this session. */
    public int getEvidenceCrushedThisSession() {
        return evidenceCrushedThisSession;
    }

    /** Returns the number of SCRAP_METAL sold this session. */
    public int getScrapMetalSoldThisSession() {
        return scrapMetalSoldThisSession;
    }

    /** Returns whether Tyson is currently distracted. */
    public boolean isTysonDistracted() {
        return tysonDistracted;
    }

    /** Force Tyson into a distracted state for testing. */
    public void setTysonDistractedForTesting(boolean distracted) {
        this.tysonDistracted = distracted;
        this.tysonDistractionTimer = distracted ? DOG_DISTRACTION_DURATION : 0f;
    }

    /** Force the weightForIt flag for testing. */
    public void setWeightForItAwardedForTesting(boolean awarded) {
        this.weightForItAwarded = awarded;
    }

    /** Force the evidenceCrushed count for testing. */
    public void setEvidenceCrushedForTesting(int count) {
        this.evidenceCrushedThisSession = count;
    }
}
